### ISSUE TITLE
Not able to generate Credit Note Against Sales Return

### ISSUE THREAD

**Issue by erpwala** [f-9t9it/pos_bahrain#135]
1. Not able to generate Credit Note Against Sales Return, if customer returns item 
2. Advance paid by customer need to adjust in mode of payments.
3. Loyalty Points is Missing

**Comment by f-9t9it** [comment]
1. Not sure about this, Please explain in detail and also explain which doctype are you point this to.
2. if customer have credit balance in his account then in POS if the user doesn't select any MOP then it will be adjusted from the customers credit balance. This is as per the Frappe/ERPNext method We have not done anything to this.
3. Yes Loyalty Point redemption is not available at this point but we do plan to get it ready, as we have already added it to our other retail business app.

If you would like to contribute to this app then please do so. 

Thank You.

**Comment by f-9t9it** [comment]
No update on this? Then I will close it for now until any update.
