### ISSUE TITLE
 Error Row 1 with ITEM has only 0, EVEN THOUGH STOCK ARE PRESENT 

### ISSUE THREAD

**Issue by erpwala** [f-9t9it/pos_bahrain#136]
Error Row 1 with ITEM has only 0, EVEN THOUGH STOCK ARE PRESENT

**Comment by f-9t9it** [comment]
Please share screenshot and this can be due to many things.

We would need more detailed information to understand this issue.

**Comment by robobird-in** [comment]
![image](https://user-images.githubusercontent.com/7752116/68854451-114fe880-0702-11ea-9a78-75c05d584c99.png)
above screen shows error
and also stock in pos showing 0


![image](https://user-images.githubusercontent.com/7752116/68854588-57a54780-0702-11ea-96ac-dca7664c0af6.png)

Above screen shows stock balance

**Comment by robobird-in** [comment]
Items have stocks but at POS screen Shows (Stock Qty: 0) in all items.

**Comment by spikerguy** [comment]
@robobird-in Please check if the item is in the same warehouse. As I dont see warehouse filter anywhere in the screenshot.

**Comment by f-9t9it** [comment]
@robobird-in Please check if the item is in the same warehouse. As I dont see warehouse filter anywhere in the screenshot.
