### ISSUE TITLE
Enhancement of Opening cash and Closing Cash Voucher

### ISSUE THREAD

**Issue by f-9t9it** [f-9t9it/pos_bahrain#16]
Enhancement of Opening cash and Closing Cash Voucher.

Currently Opening Cash is mandatory to raise closing Cash voucher. - that is fine. but if user forgot to do opening cash then closing cash is stuck in error loop.

Closing cash voucher to have time cutoff. Example: Opening cash  date time to closing cash date time.

next closing cash voucher should not pull the sales between the previous duration range.

**Comment by sunhoww** [comment]
- [ ] fetch data on save
- [ ] make datetime fields editable
- [ ] add validation to check for collision
