### ISSUE TITLE
Sales Person Item-wise Sales

### ISSUE THREAD

**Issue by bzayyat** [f-9t9it/pos_bahrain#249]
**Describe the bug**
When clicking the report "Sales Person Item-wise Sales" an error pops "pymysql.err.InternalError: (1054, "Unknown column 'sii.salesman_name' in 'field list'")"
**To Reproduce**
1. Go to : POS BAHRAIN
2. Click on : Sales Person Item-wise Sale

**Expected behavior**
Report to load
**Screenshots**
![image](https://user-images.githubusercontent.com/42342832/107660830-bc4ea980-6c99-11eb-962f-e2b4d8d48517.png)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser Chrome
 - Version 88.0.4324.150

**Additional context**
looks like the script requires an update to custom field pb_sales_employee_name

**Comment by f-9t9it** [comment]
Hello,
Thank you for informing about this.
Please share the python version you're using.

Would you like to share more information of what are you using this custom app for and which region?
Would you like to contribute to this project ?

Will look into this when we get time.

**Comment by bzayyat** [comment]
Hi There,

Version 2.7.17. 
I have a bakery in bahrain :) and would love to contribute, still going through the code though

**Comment by bzayyat** [comment]
same error with Version 3.6.9

**Comment by f-9t9it** [comment]
> I have a bakery in bahrain :) and would love to contribute, still going through the code though

Yes we are also in Bahrain, Please do contribute as we do still maintain the source code and provide it openly as an open source contribution.

It is working fine on our clients servers and we never don't face this issue. 
I have just tested and it is working fine. Maybe you have not setup the system correct.
![image](https://user-images.githubusercontent.com/39218579/107676406-27a07780-6caa-11eb-8b42-79031387e999.png)

Thank you for reporting, In my test it is working fine so I will close the issue for now. 
Appreciate your support.

**Comment by bzayyat** [comment]
let me check .. thanks
