### ISSUE TITLE
 Sales Register with Employee

### ISSUE THREAD

**Issue by bzayyat** [f-9t9it/pos_bahrain#250]
**Describe the bug**

Sales Register with Employee throws the error "StopIteration"

**Screenshots**
![image](https://user-images.githubusercontent.com/42342832/107661677-8d850300-6c9a-11eb-88f5-797ab0d7de5a.png)

**Comment by f-9t9it** [comment]
Please provide python version

**Comment by bzayyat** [comment]
2.7.17

**Comment by f-9t9it** [comment]
This one is also working fine.

**Comment by f-9t9it** [comment]
This report is working fine.
![image](https://user-images.githubusercontent.com/39218579/108094147-8ccfe080-708f-11eb-9a26-215bb86c5466.png)
