### ISSUE TITLE
Item-wise Sales Register with Employee

### ISSUE THREAD

**Issue by bzayyat** [f-9t9it/pos_bahrain#251]
**Describe the bug**
"Item-wise Sales Register with Employee" throws the error "ValueError: too many values to unpack (expected 2)"

**Screenshots**
![image](https://user-images.githubusercontent.com/42342832/107662156-0a17e180-6c9b-11eb-9cc3-afbff13de4cf.png)

**Comment by f-9t9it** [comment]
![image](https://user-images.githubusercontent.com/39218579/108094376-c7397d80-708f-11eb-85e8-bfba921b0d98.png)

Working fine.
